[project]
name = "comfyui-ppm"
description = "Fixed AttentionCouple/NegPip(negative weights in prompts), more CFG++ samplers, etc."
version = "1.0.8"
license = { text = "GNU Affero General Public License v3" }

[project.urls]
Repository = "https://github.com/pamparamm/ComfyUI-ppm"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "pamparamm"
DisplayName = "ComfyUI-ppm"
Icon = ""
